name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Correction : Passage à Node 20 pour supporter les outils de package récents
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Code Verification (Compile)
        run: npm run compile

      - name: Test Package Generation
        run: npx @vscode/vsce package # Correction : Utilisation du nouvel outil officiel de Microsoft